---
- name: PowerEdge Challenge - Return Thermal Operating Temperatures
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    idrac_ip: 10.0.0.89            # the idrac to connect to
    idrac_user: root                   # the login user that will perform the operation
    idrac_password: r0gerwilc0         # the 0 characters are zeros


  tasks:

  # Start your first task here
  - name: Get chassis thermals
    ansible.builtin.redfish_info:
      category: Chassis
      command: GetChassisThermals
      baseuri: "{{ idrac_ip }}"
      username: "{{ idrac_user }}"
      password: "{{ idrac_password }}"
    register: result

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result | to_nice_json }}"
      dest: "output.json"  # thermals are posted in a file named output.json

